/* Write your PL/SQL query statement below */
SELECT ACTOR_ID,DIRECTOR_ID FROM (
    SELECT ACTOR_ID,DIRECTOR_ID,COUNT(1)
    FROM ACTORDIRECTOR
    GROUP BY ACTOR_ID,DIRECTOR_ID
    HAVING COUNT(1)>=3
    )
