SELECT 
TO_CHAR(ACTIVITY_DATE,'YYYY-MM-DD') AS DAY,
COUNT(DISTINCT USER_ID) AS ACTIVE_USERS
FROM ACTIVITY
WHERE 
TO_CHAR(ACTIVITY_DATE,'YYYY-MM-DD') BETWEEN '2019-06-26' AND '2019-07-27'
GROUP BY TO_CHAR(ACTIVITY_DATE,'YYYY-MM-DD')
