/* Write your PL/SQL query statement below */
SELECT 
BUYER_ID,JOIN_DATE,
SUM(CASE WHEN EXTRACT(YEAR FROM ORDER_DATE)=2019 THEN 1 ELSE 0 END) ORDERS_IN_2019
FROM(
    SELECT 
    U.USER_ID AS BUYER_ID,
    TO_CHAR(U.JOIN_DATE,'YYYY-MM-DD') JOIN_DATE,
    O.ORDER_DATE
    FROM USERS U
    LEFT JOIN
    ORDERS O
    ON U.USER_ID=O.BUYER_ID)
GROUP BY BUYER_ID,JOIN_DATE
ORDER BY BUYER_ID
​
​
