/* Write your PL/SQL query statement below */
SELECT
V.CUSTOMER_ID,
COUNT(1) AS COUNT_NO_TRANS
FROM VISITS V
LEFT JOIN Transactions T
ON V.VISIT_ID=T.VISIT_ID
WHERE T.VISIT_ID IS NULL
GROUP BY V.CUSTOMER_ID;
