/* Write your PL/SQL query statement below */
SELECT SECONDHIGHESTSALARY FROM (
SELECT SALARY AS SECONDHIGHESTSALARY FROM (
SELECT SALARY,
DENSE_RANK() OVER(ORDER BY SALARY DESC) RN
FROM EMPLOYEE)
WHERE RN=2
UNION
SELECT NULL AS SECONDHIGHESTSALARY FROM DUAL)
WHERE ROWNUM=1
