/* Write your PL/SQL query statement below */
SELECT (
SELECT DISTINCT SALARY 
FROM(
    SELECT 
    SALARY,
    DENSE_RANK() OVER(ORDER BY SALARY DESC) RN
    FROM EMPLOYEE
    )
WHERE RN=2) AS SECONDHIGHESTSALARY
FROM DUAL
