/* Write your PL/SQL query statement below */
WITH CTE AS(
    SELECT 
    SALARY,
    DENSE_RANK() OVER(ORDER BY SALARY DESC) RN
    FROM EMPLOYEE
    )
SELECT SECONDHIGHESTSALARY FROM (
    SELECT SALARY AS SECONDHIGHESTSALARY FROM CTE WHERE RN=2
    UNION
    SELECT NULL AS SECONDHIGHESTSALARY FROM DUAL)
WHERE ROWNUM=1;
