CREATE FUNCTION getNthHighestSalary(N IN NUMBER) RETURN NUMBER IS
result NUMBER;
BEGIN
    SELECT SALARY INTO RESULT FROM (
        SELECT SALARY FROM (
            SELECT SALARY, DENSE_RANK() OVER(ORDER BY SALARY DESC) RN
            FROM EMPLOYEE)
        WHERE RN=N
        UNION
        SELECT NULL AS SALARY FROM DUAL
    ) WHERE ROWNUM=1;
    RETURN result;
END;
