/* Write your PL/SQL query statement below */
SELECT DISTINCT NUM AS CONSECUTIVENUMS FROM(
SELECT 
NUM,
LEAD(NUM,1) OVER(ORDER BY ID) SECOND,
LEAD(NUM,2) OVER(ORDER BY ID) THIRD
FROM LOGS)
WHERE NUM=SECOND AND NUM=THIRD
