SELECT DEPARTMENT,EMPLOYEE,SALARY FROM(
SELECT E.NAME EMPLOYEE,E.SALARY,D.NAME DEPARTMENT,
DENSE_RANK() OVER(PARTITION BY D.NAME ORDER BY E.SALARY DESC) RN
FROM EMPLOYEE E INNER JOIN
DEPARTMENT D ON E.DEPARTMENTID=D.ID)
WHERE RN<=3
