/* Write your PL/SQL query statement below */
WITH CAT AS(
    SELECT 'Low Salary' AS CATEGORY FROM DUAL
    UNION
    SELECT 'Average Salary' AS CATEGORY FROM DUAL
    UNION
    SELECT 'High Salary' AS CATEGORY FROM DUAL
),
CTE AS(
    SELECT
    CASE
        WHEN INCOME<20000 THEN 'Low Salary'
        WHEN INCOME>=20000 AND INCOME<=50000 THEN 'Average Salary'
        ELSE 'High Salary'
    END AS CATEGORY,
    INCOME
    FROM ACCOUNTS
)
SELECT
A.CATEGORY,
COUNT(B.INCOME) ACCOUNTS_COUNT
FROM CAT A
LEFT JOIN CTE B
ON A.CATEGORY=B.CATEGORY
GROUP BY A.CATEGORY
