/* Write your PL/SQL query statement below */
SELECT
S.USER_ID,
ROUND(SUM(CASE WHEN C.ACTION = 'confirmed' THEN 1 ELSE 0 END)/COUNT(1),2) AS CONFIRMATION_RATE
FROM SIGNUPS S
LEFT JOIN
CONFIRMATIONS C
ON S.USER_ID = C.USER_ID
GROUP BY S.USER_ID
