/* Write your PL/SQL query statement below */
SELECT
COALESCE(E.EMPLOYEE_ID,S.EMPLOYEE_ID) AS EMPLOYEE_ID
FROM EMPLOYEES E
FULL OUTER JOIN
SALARIES S
ON E.EMPLOYEE_ID=S.EMPLOYEE_ID
WHERE E.NAME IS NULL OR S.SALARY IS NULL
ORDER BY 1
