/* Write your PL/SQL query statement below */
SELECT ID FROM (
    SELECT
    ID,
    RECORDDATE,
    TEMPERATURE AS TEMP,
    LAG(TEMPERATURE) OVER(ORDER BY RECORDDATE) AS PREV_TEMP,
    LAG(RECORDDATE) OVER(ORDER BY RECORDDATE) AS PREV_DATE
    FROM WEATHER)
WHERE TEMP>PREV_TEMP AND RECORDDATE-1=PREV_DATE;
