/* Write your PL/SQL query statement below */
SELECT ID
FROM(
    SELECT
    ID,
    TEMPERATURE,
    RECORDDATE,
    LAG(TEMPERATURE) OVER(ORDER BY RECORDDATE) PREV_TEMP,
    LAG(RECORDDATE) OVER(ORDER BY RECORDDATE) PREV_DATE
    FROM WEATHER
    )
WHERE TEMPERATURE>PREV_TEMP
AND RECORDDATE-PREV_DATE=1
