/* Write your PL/SQL query statement below */
SELECT
E.EMPLOYEE_ID
FROM EMPLOYEES E
LEFT JOIN 
EMPLOYEES M
ON E.MANAGER_ID=M.EMPLOYEE_ID
WHERE E.MANAGER_ID IS NOT NULL
AND E.SALARY<30000
AND M.EMPLOYEE_ID IS NULL
ORDER BY E.EMPLOYEE_ID
