WITH CTE AS(
    SELECT
    S.INVOICE_ID,
    P.PRODUCT_ID,
    S.QUANTITY,
    S.QUANTITY*P.PRICE AS PRICE,
    SUM(S.QUANTITY*P.PRICE) OVER(PARTITION BY S.INVOICE_ID) AS SUMM
    FROM PRODUCTS P
    INNER JOIN PURCHASES S
    ON P.PRODUCT_ID = S.PRODUCT_ID)
SELECT
PRODUCT_ID,QUANTITY,PRICE
FROM (
    SELECT
    PRODUCT_ID,QUANTITY,PRICE,
    DENSE_RANK() OVER(ORDER BY SUMM DESC,INVOICE_ID) AS RN
    FROM CTE)
WHERE RN=1
