/* Write your PL/SQL query statement below */
SELECT CUSTOMER_NUMBER FROM(
    SELECT
    CUSTOMER_NUMBER,COUNT(1)
    FROM ORDERS
    GROUP BY CUSTOMER_NUMBER
    ORDER BY COUNT(1) DESC)
WHERE ROWNUM=1
